### ISSUE TITLE
Trying to run experiments...

### ISSUE THREAD

**Issue by ugurbolat** [JerryLingjieMei/ADEPT-Model-Release#2]
Hi,

I am trying to run the code by following the README. So far, I completed the installation part but I am stuck at the experiments part:

1. I set the train and human path variables to the 'data_sample' folder and created annotation json files. Skipped the training the detection part since I want to use the downloaded pre-trained networks
2. make_proposal script does not work because there is no such file called 'segm.json' somewhere in the project. I am not sure which script produces this file...
3. tried to run_physics but it does not output the results file

What am I missing?

**Comment by JerryLingjieMei** [comment]
Thanks for your information. So 'segm.json' is provided by the inference using detection module, and make_proposal is using that inference result to train a derender module. You will need to make an inference using the downloaded weights for detection and use the segm.json and pass it to the derenderer.

**Comment by ugurbolat** [comment]
# Installation Issues

- requirements.txt
  - numpy (this has to be 1.17, higher versions don't work)

- conda install pytorch=1.1.0 cuda100 -c pytorch
  - this pytorch version is also compatible with maskrcnn but it isn't backward compatible. the version maskrcnn's current installation guide refers pytorch-nightly (pytorch 1.0.0)
- MaskRCNN bug
  - install torchvision=0.2.1, higher versions don't work.
  - KeyError: 'Non-existent config key: MODEL.BACKBONE.OUT_CHANNELS'
    - I also faced with this issue: [#1](https://github.com/JerryLingjieMei/ADEPT-Model-Release/issues/1)
    - Like you told it is because FB changed their config file keys so you have to revert the repo to the earlier commit before they change it, which is [Supported FBNet architecture. (#463) · facebookresearch/maskrcnn-benchmark@b23eee0](https://github.com/facebookresearch/maskrcnn-benchmark/commit/b23eee0cb72af70f4e4a72e73537f0884cfd1cff)
      - git checkout 192261db14d596da52905e91dc608bd4315552dc
    - Some ppl suggest to install [Cadene/vqa-maskrcnn-benchmark](https://github.com/Cadene/vqa-maskrcnn-benchmark) (which is an alternative repo to original FB repo) but it does not work with the ADEPT.
  - But when you revert to the commit I mentioned, you will have this bug that they fixed in the later commit:
    - You have to modify the source url location in model_zoo.py: [APIs moved to torch.hub by thomasshupeng · Pull Request #673 · facebookresearch/maskrcnn-benchmark](https://github.com/facebookresearch/maskrcnn-benchmark/pull/673/files)
  - I've faced to a compilation error while install apex (probably related to CUDA) so I skip the building from source, instead I ignore '--cuda_ext --cpp_ext'. I didn't test the training by parallelizing to multi-GPU tho.

- Scripts related to ADEPT model:
  - Although I set the paths mentioned in the instruction according to my setup, I had an issue with the yaml files in the data_sample folder. Some path variables are left hardcoded in the file (such as '/root/adept-model/data_sample/human/'). While running make_proposal.py script, it can't find the path of images even if it HUMAN_TEST_SET_FOLDER variable set correctly.
